EXPECTED_MAP = {
    "nb_drones": 5,
    "start_hub": "start",
    "end_hub": "goal",
    "hubs": {
        "start": {
            "name": "start",
            "x": 0,
            "y": 0,
            "zone_type": "normal",
            "color": "green",
            "max_drones": 1,
        },
        "junction": {
            "name": "junction",
            "x": 1,
            "y": 0,
            "zone_type": "normal",
            "color": "yellow",
            "max_drones": 2,
        },
        "dead_end": {
            "name": "dead_end",
            "x": 1,
            "y": 1,
            "zone_type": "normal",
            "color": "red",
            "max_drones": 1,
        },
        "correct_path": {
            "name": "correct_path",
            "x": 2,
            "y": 0,
            "zone_type": "normal",
            "color": "blue",
            "max_drones": 1,
        },
        "intermediate": {
            "name": "intermediate",
            "x": 3,
            "y": 0,
            "zone_type": "normal",
            "color": "blue",
            "max_drones": 1,
        },
        "goal": {
            "name": "goal",
            "x": 4,
            "y": 0,
            "zone_type": "normal",
            "color": "green",
            "max_drones": 1,
        },
    },
    "connections": [
            {
                "from_hub": "start",
                "to_hub": "junction",
                "max_link_capacity": 2,
            },
            {
                "from_hub": "junction",
                "to_hub": "dead_end",
                "max_link_capacity": 1,
            },
            {
                "from_hub": "junction",
                "to_hub": "correct_path",
                "max_link_capacity": 1,
            },
            {
                "from_hub": "correct_path",
                "to_hub": "intermediate",
                "max_link_capacity": 1,
            },
            {
                "from_hub": "intermediate",
                "to_hub": "goal",
                "max_link_capacity": 1,
            },
        ],
}
