EXPECTED_MAP = {
    "nb_drones": 6,
    "start_hub": "start",
    "end_hub": "goal",
    "hubs": {
        "start": {
            "name": "start",
            "x": 0,
            "y": 0,
            "zone_type": "normal",
            "color": "green",
            "max_drones": 1,
        },
        "loop_a": {
            "name": "loop_a",
            "x": 1,
            "y": 0,
            "zone_type": "normal",
            "color": "orange",
            "max_drones": 2,
        },
        "loop_b": {
            "name": "loop_b",
            "x": 2,
            "y": 0,
            "zone_type": "normal",
            "color": "orange",
            "max_drones": 2,
        },
        "loop_c": {
            "name": "loop_c",
            "x": 2,
            "y": 1,
            "zone_type": "normal",
            "color": "orange",
            "max_drones": 2,
        },
        "loop_d": {
            "name": "loop_d",
            "x": 1,
            "y": 1,
            "zone_type": "normal",
            "color": "orange",
            "max_drones": 2,
        },
        "exit_point": {
            "name": "exit_point",
            "x": 3,
            "y": 0,
            "zone_type": "restricted",
            "color": "blue",
            "max_drones": 1,
        },
        "goal": {
            "name": "goal",
            "x": 4,
            "y": 0,
            "zone_type": "normal",
            "color": "red",
            "max_drones": 1,
        },
    },
    "connections": [
            {
                "from_hub": "start",
                "to_hub": "loop_a",
                "max_link_capacity": 2,
            },
            {
                "from_hub": "loop_a",
                "to_hub": "loop_b",
                "max_link_capacity": 2,
            },
            {
                "from_hub": "loop_b",
                "to_hub": "loop_c",
                "max_link_capacity": 2,
            },
            {
                "from_hub": "loop_c",
                "to_hub": "loop_d",
                "max_link_capacity": 2,
            },
            {
                "from_hub": "loop_d",
                "to_hub": "loop_a",
                "max_link_capacity": 2,
            },
            {
                "from_hub": "loop_b",
                "to_hub": "exit_point",
                "max_link_capacity": 1,
            },
            {
                "from_hub": "exit_point",
                "to_hub": "goal",
                "max_link_capacity": 1,
            },
        ],
}
