EXPECTED_MAP = {
    "nb_drones": 5,
    "start_hub": "start",
    "end_hub": "goal",
    "hubs": {
        "start": {
            "name": "start",
            "x": 0,
            "y": 0,
            "zone_type": "normal",
            "color": "green",
            "max_drones": 1,
        },
        "slow_path1": {
            "name": "slow_path1",
            "x": 1,
            "y": -1,
            "zone_type": "restricted",
            "color": "red",
            "max_drones": 1,
        },
        "slow_path2": {
            "name": "slow_path2",
            "x": 2,
            "y": -1,
            "zone_type": "normal",
            "color": "red",
            "max_drones": 1,
        },
        "fast_junction": {
            "name": "fast_junction",
            "x": 1,
            "y": 0,
            "zone_type": "priority",
            "color": "blue",
            "max_drones": 2,
        },
        "fast_path": {
            "name": "fast_path",
            "x": 2,
            "y": 0,
            "zone_type": "priority",
            "color": "blue",
            "max_drones": 1,
        },
        "merge_point": {
            "name": "merge_point",
            "x": 3,
            "y": 0,
            "zone_type": "normal",
            "color": "yellow",
            "max_drones": 3,
        },
        "goal": {
            "name": "goal",
            "x": 4,
            "y": 0,
            "zone_type": "normal",
            "color": "green",
            "max_drones": 1,
        },
    },
    "connections": [
            {
                "from_hub": "start",
                "to_hub": "slow_path1",
                "max_link_capacity": 1,
            },
            {
                "from_hub": "start",
                "to_hub": "fast_junction",
                "max_link_capacity": 1,
            },
            {
                "from_hub": "slow_path1",
                "to_hub": "slow_path2",
                "max_link_capacity": 1,
            },
            {
                "from_hub": "slow_path2",
                "to_hub": "merge_point",
                "max_link_capacity": 1,
            },
            {
                "from_hub": "fast_junction",
                "to_hub": "fast_path",
                "max_link_capacity": 1,
            },
            {
                "from_hub": "fast_path",
                "to_hub": "merge_point",
                "max_link_capacity": 1,
            },
            {
                "from_hub": "merge_point",
                "to_hub": "goal",
                "max_link_capacity": 2,
            },
        ],
}
